### ISSUE TITLE
Display function signature

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus-python#103]
The `display` function should have the same signature as the one from IPython. For example the IPython display function takes a list of objects to display, not a single object.

**Comment by martinRenou** [comment]
It is actually not easy to replicate the
```python
def display(*objs, include=None, exclude=None, metadata=None, transient=None, display_id=None, **kwargs):
```
signature, as `pybind11` only allows to have `py::args` at last arguments.

**Comment by SylvainCorlay** [comment]
@martinRenou should we close this?

**Comment by martinRenou** [comment]
Not quite. The signature has been improved but is still not the same.

**Comment by martinRenou** [comment]
This has been fixed
