### ISSUE TITLE
Matplotlib support

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus-python#105]
We should think about Matplotlib support. Maybe implement a custom backend, or try to reuse the notebook back-end.

**Comment by martinRenou** [comment]
This should be possible using https://github.com/matplotlib/jupyter-matplotlib

But the library does an `from IPython.display import display, HTML` which is not possible due to this issue #106. So we need to either fix #106 or replace the import in jupyter-matplotlib by:

```python
from IPython.display import display
from IPython.lib.display import HTML
```

**Comment by SylvainCorlay** [comment]
One thing we should try to *not* do is the hardcoding of matplotlib backends that are listed in IPython.

**Comment by SylvainCorlay** [comment]
Closing as superseeded by #224.
