### ISSUE TITLE
Support for async / await

### ISSUE THREAD

**Issue by jtpio** [jupyter-xeus/xeus-python#175]
It would be nice to have support for async / await at the top-level. At the moment the kernel does not respond when using the following code snippet:

```python
import asyncio
await asyncio.sleep(2)
```

![xpython-asyncio](https://user-images.githubusercontent.com/591645/69091325-5b123900-0a4a-11ea-8185-71074a13807a.gif)

Here are the logs after setting `XEUS_LOG=1` and interrupting the kernel (see screencast above):

```
XEUS: sent message on iopub - kernel_core.f23afc045e2740f0abf2fd97d9b28e26.execute_input
msg_type: execute_input
ERROR: during execute_request
make_tuple(): unable to convert arguments to Python object (compile in debug mode for details)
XEUS: sent message on iopub - kernel_core.f23afc045e2740f0abf2fd97d9b28e26.status
msg_type: status
terminate called after throwing an instance of 'zmq::error_t'
  what():  Interrupted system call[I 21:25:59.177 LabApp] Kernel interrupted: c6315021-3d48-4b8a-936d-1d013872d051

[I 21:26:01.900 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
```

Tested with xeus-python 0.6.6.

**Comment by martinRenou** [comment]
This is fixed now that xeus-python depends on IPython 

![asyncio](https://user-images.githubusercontent.com/21197331/132828223-c4206f44-aa3c-4176-961c-9a503efb1bc4.gif)
