### ISSUE TITLE
Code completion inconsistent after "."

### ISSUE THREAD

**Issue by aolney** [jupyter-xeus/xeus-python#196]
I can get a list of options with the following:

```python
import nltk
nltk.<TAB> #works
```

However, nothing happens if I do this:

```python
import spacy
spacy.<TAB> #fails
```

Curiously if I give an extra letter, I will get completions with that letter:

```python
import spacy
spacy.l<TAB> #works
```

It looks like `jedi` is being used for the completions, but I haven't managed to construct a useful test case with it to figure out what's going on.

Is this a `xeus-python` problem, a `jedi` problem, or a problem with `spacy`, i.e. docstrings not compatible?

**Comment by JohanMabille** [comment]
Do you have the same issue with ipykernel / ipython?

**Comment by martinRenou** [comment]
It seems to be an issue with `spacy` specifically, I get the following error message when trying to complete `spacy.<TAB>`:

```
ERROR: received bad message: TypeError: issubclass() arg 1 must be a class

At:
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/access.py(497): _is_class_instance
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/access.py(304): is_instance
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/subprocess/functions.py(21): get_compiled_method_return
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/subprocess/__init__.py(406): _cached_results
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/cache.py(143): wrapper
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/subprocess/__init__.py(398): _workaround
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/context.py(119): is_instance
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/gradual/conversion.py(169): to_stub
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/mixed.py(249): _create
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/access.py(122): wrapper
  /home/martin/miniconda3/envs/xeus-python/lib/python3.7/site-packages/jedi/evaluate/compiled/mixed.py(111): <genexpr>

Message content: {"code":"spacy.","cursor_pos":6}
```

I'll investigate a bit more.

**Comment by martinRenou** [comment]
I opened an issue in `jedi`, I think it is safe to close this issue. Even using the last `jedi` version it seems to fail.

**Comment by aolney** [comment]
Thank you @martinRenou :thumbsup:

**Comment by martinRenou** [comment]
It has been fixed upstream :) So we need to wait for a jedi release and then we need to update the jedi version requirement in xeus-python

**Comment by martinRenou** [comment]
Thanks for opening an issue!

**Comment by aolney** [comment]
Thank you for your responsiveness and contributions to this project. I'm using it in a class I'm teaching, and it has been great :thumbsup:

**Comment by martinRenou** [comment]
Thanks for the kind words!
