### ISSUE TITLE
Add xeus-python in existing python environment ?

### ISSUE THREAD

**Issue by rquintino** [jupyter-xeus/xeus-python#206]
I wanted to give the new jupyter lab debugger a try (https://github.com/jupyterlab/debugger), from what I've read requires, xeus-python. 

It would be great to just plug this onto our existing python envs, docker based, very often without conda/miniconda. Anyone knows if this is possible? 

Thanks!

**Comment by JohanMabille** [comment]
We are working on a [wheel](https://github.com/jupyter-xeus/xeus-python-wheel) for xeus-python. It should be available soon, stay tuned!

**Comment by SylvainCorlay** [comment]
Hi @rquintino we now have an experimental wheel up on PyPI - linux 64 only.

**Comment by SylvainCorlay** [comment]
Closing as a duplicate of #181.
