### ISSUE TITLE
xpython does not pass the required include and exclude arguments to _repr_mimebundle_

### ISSUE THREAD

**Issue by josephsmann** [jupyter-xeus/xeus-python#221]
when plotting an altair graph in a jupyter lab note book, I got the error:

TypeError: repr_mimebundle() missing 2 required positional arguments: 'include' and 'exclude'

I raised this with the altair people eg. @jakevdp and they thought it best that I raise it here.

Here is what I tried:
```
import altair as alt
alt.Chart(pd.DataFrame({'a': [1, 2, 3], 'b':[4, 0, 9]})).mark_point().encode(
    x='a:Q',
    y='b:Q')
```
and here is the complete error message: 

```
TypeError Traceback (most recent call last)
In [11]:
Line 1: points

TypeError: repr_mimebundle() missing 2 required positional arguments: 'include' and 'exclude'
```
here is my config :
XEUS 0.23.9
jupyter core : 4.6.3
jupyter-notebook : 6.0.3
qtconsole : not installed
ipython : 7.13.0
ipykernel : 5.2.0
jupyter client : 6.1.1
jupyter lab : 2.0.1
nbconvert : 5.6.1
ipywidgets : not installed
nbformat : 5.0.4
traitlets : 4.3.3
altair. : 4.0.1

**Comment by jakevdp** [comment]
See https://github.com/ipython/ipython/blob/a2685d78f2403f84e6cb915ae11a4f6033ccc5f6/examples/IPython%20Kernel/Custom%20Display%20Logic.ipynb
for information.

**Comment by martinRenou** [comment]
Indeed it has not been implemented yet. I'll have a look at it.
