### ISSUE TITLE
Running xpython (from pip) fails with `ModuleNotFoundError: No module named 'jedi'` despite jedi being installed.

### ISSUE THREAD

**Issue by koenlek** [jupyter-xeus/xeus-python#228]
I installed it like this:

```sh
pip3 install xeus-python
```

When I try to run (as root, this is in a dockerized env), it crashes:

```
# xpython
registering handler for SIGSEGV
PYTHONHOME set to /usr/local/bin/../
Python sys.path set to :/usr/local/bin/..//lib/python36.zip:/usr/local/bin/..//lib/python3.6:/usr/local/bin/..//lib/python3.6/lib-dynload:/usr/local/bin/..//lib/python3.6/site-packages:/usr/local/bin/..//../lb/python36.zip:/usr/local/bin/..//../lib/python3.6:/usr/local/bin/..//../lib/python3.6/lib-dynload:/usr/local/bin/..//../lib/python3.6/site-packages:/usr/local/bin/..//lib64/python36.zip:/usr/local/bin/..//lib64/python3.6:/usr/local/bin/..//lib64/python3.6/lib-dynload:/usr/local/bin/..//lib64/python3.6/site-packages:/usr/local/bin/..//../lib64/python36.zip:/usr/local/bin/..//../lib64/python3.6:/usr/local/bin/..//../lib64/python3.6/lib-dynload:/usr/local/bin/..//../lib64/python3.6/site-packages:
terminate called after throwing an instance of 'pybind11::error_already_set'
  what():  ModuleNotFoundError: No module named 'jedi'
Aborted (core dumped)
```

Despite jedi definitely being installed and up to date:

```sh
pip3 install --upgrade jedi
# just to be sure:
pip2 install --upgrade jedi

python3 -c "import jedi; print(jedi.__version__)"
> 0.16.0
```

And I have xeus_python-0.6.13 and jupyter lab version 1.2.5.

**Comment by SylvainCorlay** [comment]
Hey @koenlek thanks for reporting.

FYI, the PyPI wheels are still [**experimental**](https://xeus-python.readthedocs.io/en/latest/installation.html#from-pypi), and we recommend using a package manager, such as conda. We maintain conda-forge packages for xeus-python.

However, we are working hard on streamlining the wheels, so it would be great if you could provide us with some more info:

 - could you please give me the value of `sys.path` when running Python 3? Linux distributions patch CPython to change the sys path, and we need to adapt to all the cases.

**Comment by koenlek** [comment]
Hi @SylvainCorlay. Thanks for your fast reply. Unfortunately, conda is no viable option for me, as I'm using jupyter from a lean docker container (and although I could install conda in that, I'm not planning to take that much of a detour for this purpose).

`sys.path` from python3:

```py
['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']
```

Jedi is installed under `/usr/local/lib/python3.6/dist-packages`

**Comment by SylvainCorlay** [comment]
>  docker container 

Cool. Conda works great in docker containers though. You may be interested in repo2docker for automatically generating docker images with the scientific software stack that you need.

> sys.path from python3:

Thanks! I would also need your `sys.prefix` value (whether it is `/usr` or `/usr/local`). Sorry for missing that earlier. (The good news is that the fix is very simple. The bad news is that we need to upload a new version of the wheel.)

**Comment by koenlek** [comment]
`sys.prefix` is `/usr`.

Any plans to support python2 as well? Currently I can only install it through pip3, so I assume it's a python3 only kernel? I wouldn't blame you of you don't plan on supporting python2... It's just that I'm tied to still running many things in python2...

**Comment by koenlek** [comment]
@SylvainCorlay , I noticed your fix here: https://github.com/jupyter-xeus/xeus-python-wheel/pull/32. I build it locally (`python3 setup.py bdist_wheel`) and install it in the container and can confirm that it works now.

Thanks! Looking forward to see it released to the pypi.

**Comment by dfayzur** [comment]
Hi,
I am having the same error. Can you guide me the way to solve it?

**Comment by SylvainCorlay** [comment]
Hey @dfayzur 

FYI, the PyPI wheels are still [**experimental**](https://xeus-python.readthedocs.io/en/latest/installation.html#from-pypi), and we recommend using a package manager, such as conda. We maintain [**conda-forge packages**](https://xeus-python.readthedocs.io/en/latest/installation.html#with-conda) for xeus-python.

However, we are working on streamlining the wheels. We will keep people updated on this thread when we update the package.

**Comment by SylvainCorlay** [comment]
@koenlek @dfayzur closing as we have release 0.7.0 and 0.7.1 fixing that issue.
