### ISSUE TITLE
Virtual environment kernel

### ISSUE THREAD

**Issue by jmrichardson** [jupyter-xeus/xeus-python#229]
Hi,

With ipython you can install a kernel for jupyterlab  to use (which I have in another environment):

`ipython kernel install --user --name=myenv`

Is there a similar command for xeus-python?  TIA

**Comment by pmav99** [comment]
In the jupyter environment, try to use `jupyter kernelspec install`. It is mentioned in the docs, too:
https://xeus-python.readthedocs.io/en/latest/installation.html#installing-the-kernel-spec

**Comment by SylvainCorlay** [comment]
Indeed! `jupyter kernelspec install` can be used to install kernelspecs in other prefixes.

https://xeus-python.readthedocs.io/en/latest/installation.html#installing-the-kernel-spec

Thanks for posting.

**Comment by SylvainCorlay** [comment]
Another note:

Please bear with us with respect to the Python wheel which is still experimental. We recommend using conda.

**Comment by jmrichardson** [comment]
@SylvainCorlay @pmav99 Thank you but I am still having trouble getting it to work.  I have jupyterlab installed in an virtual enivornment called jupyterlab.  I also have another virtual environment called amdocs.  I want to be able to run jupyterlab from the jupyterlab environment and choose the kernel from the amdocs virtual environment.  I have tried multiple ways to add the kernelspec so that jupyterlab picks it up:

```
jupyter kernelspec install D:\Anaconda3\envs\amdocs\share\jupyter\kernels\xpython
[InstallKernelSpec] Removing existing kernelspec in C:\ProgramData\jupyter\kernels\xpython
[InstallKernelSpec] Installed kernelspec xpython in C:\ProgramData\jupyter\kernels\xpython
```
However, the above doesn't work.  Looking at the kernel.json in both separate environment, they are identical and not sure if that has anything to do with it:

```
{
  "display_name": "xpython",
  "argv": [
      "D:/bld/xeus-python_1585147663623/_h_env/Library/bin/xpython",
      "-f",
      "{connection_file}"
  ],
  "language": "python"
}
```
Sorry in advance if I am missing something simple

**Comment by jmrichardson** [comment]
Nevermind, I am just going to install jupyterlab in each of the virtual environments.  Thanks anyways
