### ISSUE TITLE
Plot function hangs in Windows but not Linux

### ISSUE THREAD

**Issue by aolney** [jupyter-xeus/xeus-python#245]
Originally posted [here for pyLDAvis](https://github.com/bmabey/pyLDAvis/issues/164#issue-592970358).

The following code hangs in JupyterLab on Windows 10 but not Linux:

```python
import pyLDAvis as vis
import pyLDAvis.gensim as visGen
import matplotlib.pyplot as plt

visualization = visGen.prepare(lda, matrix, dictionary)
```
On Windows, if I switch to the Python 3 kernel in JLab, it works; if I 
save the JupyterLab notebook at a Python script, and execute it at the command line in Windows, the above code works.

Any thoughts on this inconsistent behavior across platforms?

**Comment by martinRenou** [comment]
Matplotlib is really tight to IPython currently. Adding Matplotlib support in xeus-python is not trivial without making ugly hacks. An issue has been opened for this #224.

**Comment by aolney** [comment]
Thanks for the fast response :) I want to stress that it does work in Linux, so my guess is that this is a cross platform issue (at least in this specific case).

**Comment by martinRenou** [comment]
Mmh ok. It might be something else.

Would you mind providing a reproducible code snippet? The code you provide cannot work even on Linux. It's missing variables.

Do you get an error on Windows?

**Comment by aolney** [comment]
On Windows, there was no obvious error, but the terminal output for xpython seemed to suggest it shifted into a different mode of operation, possibly a failed attempted restart. After the output below, it just hangs and needs a ctrl-C to even shut down.

```
Starting xeus-python kernel...

If you want to connect to this kernel from an other client, you can use the C:\Users\Andrew Olney\AppData\Roaming\jupyter\runtime\kernel-33b0b04d-1493-488b-b10e-cec7616eebf4.json file.
Run with XEUS 0.23.10
[I 10:50:31.663 LabApp] Saving file at /xeus-plot-hang-mwe.ipynb
PYTHONHOME set to PYTHONHOME set to C:\Users\Andrew Olney\.conda\envs\iis4011\Library\bin\..\..\C:\Users\Andrew Olney\.conda\envs\iis4011\Library\bin\..\..\PYTHONHOME set to

Python sys.path set to C:\Users\Andrew Olney\.conda\envs\iis4011\Library\bin\..\..\C:\Users\Andrew Olney\.conda\envs\iis4011\python37.zip;C:P
yth\PoUyn tsehsyorsns. \psyaAsth.ndp rasetethw   tsOoet lne C:ty\o\U .conCse:dr\asU\es\Aennrsdv\reAs\nw diOriles4wne 01Olne1yy\\\L..ccioonnbrddaa\raey\nvens\b\viiinss\.4\i0.is\1401.11.\\pp\yy\ttDhhooLnn33Ls77..;Czz:ii\pp;;UC:sC:\User\esUs\rs\eAAnnrdrsdewr\ eAOwnl Ondlereynw e\Oy\l..ncceooy\nndd.caa\\oneenndvvass\envs\\\iiiiiisss44401001\1111Li\\brLLariiybrabra\rrbyyi\\bbn\ii.nn.\\..\...\\.....\\\\\DD\LLLLlissb;C:\;;UC:sC\e:Ur\Usss\eeArsnrsd\Ar\Aennw ddOrelrew nwOeyl \nO.elcyne\.yoc\nond.daca\o\enenvnds\avi\eisnv\s4is0i\1sii41s0\41L01i11b\Lr\iaLbrirabrry\yar\bibynin\\
bin\..\..\\lib;C:\Users\Andrew Olney\.conda\envs\iis4011\Library\bin..\..\\lib;C:\Users\Andrew Olney\.conda\envs\iis4011\Library\bin

Starting xeus-python kernel...

If you want to connect to this kernel from an other client, just copy and paste the following content inside of a `kernel.json` file. And then run for example:

# jupyter console --existing kernel.json

kernel.json
```
{
    "transport": "tcp",
    "ip": "127.0.0.1",
    "control_port": 58495 ,
    "shell_port": 64787 ,
    "stdin_port": 59684 ,
    "iopub_port": 61666 ,
    "hb_port": 62973 ,
    "signature_scheme": "hmac-sha256",
    "key": "cf55f2ec3ca449cb86b111cadf817539"
}
```
Starting xeus-python kernel...

If you want to connect to this kernel from an other client, just copy and paste the following content inside of a `kernel.json` file. And then run for example:

# jupyter console --existing kernel.json

kernel.json
```
{
    "transport": "tcp",
    "ip": "127.0.0.1",
    "control_port": 57870 ,
    "shell_port": 59412 ,
    "stdin_port": 55632 ,
    "iopub_port": 64984 ,
    "hb_port": 58259 ,
    "signature_scheme": "hmac-sha256",
    "key": "8516b3450c7940db924a68ab0ff85210"
}
```
Run with XEUS Run with XEUS 00..2233..1100

Starting xeus-python kernel...

If you want to connect to this kernel from an other client, just copy and paste the following content inside of a `kernel.json` file. And then run for example:

# jupyter console --existing kernel.json

kernel.json
```
{
    "transport": "tcp",
    "ip": "127.0.0.1",
    "control_port": 52726 ,
    "shell_port": 63147 ,
    "stdin_port": 52559 ,
    "iopub_port": 65147 ,
    "hb_port": 51004 ,
    "signature_scheme": "hmac-sha256",
    "key": "be2cd360933a4214a5a50506d69ce379"
}
```
Run with XEUS 0.23.10
```
Here is a MWE, though it arguably could be trimmed down a bit more:

[notebook for mwe, xpython kernel](https://drive.google.com/open?id=1p7UwCKZZHRxbyYJTabc1QqRjyL47Vho3)

[data for mwe](https://drive.google.com/open?id=1Rh_i8LXNZlRNRbdRtxP1_B9AWJzN1UVE)
