### ISSUE TITLE
Possibility to access sys.argv

### ISSUE THREAD

**Issue by rrma** [jupyter-xeus/xeus-python#264]
Is there an option to access the input parameters provided during startup?
e.g. I should get 3 parameters (name of the notebook, param1 and param2) when running
`xpython -f my_notebook.ipynb 'param1' 'param2'`

In general, I should get the name of the jupyter-notebook when I retrieve the first argument with `sys.argv[0]`. Currently, this raises an error (as the arguments array is empty).

Sample code:
```
import sys

filename = sys.argv[0]
```

**Comment by martinRenou** [comment]
Does it work with ipykernel?

It might be easy to expose this actually.

**Comment by rrma** [comment]
yes, this is possible with ipykernel. 
It would be useful to be able to access this...

**Comment by SylvainCorlay** [comment]
@rrma We will enable the access to `argv` in 0.7.2.

Besides, it should already be possible when installing 0.7.1 from PyPI, but not with the conda package (yet). The fact that it works in the PyPI package is a byproduct of a slightly way of bootstrapping the kernel in the case of the wheel.

Note that the PyPI wheel for xeus-python is **experimental**.

**Comment by SylvainCorlay** [comment]
Fixed in #311.
