### ISSUE TITLE
how to switch xpython kernels between different venv ( under Jupiter Lab )?

### ISSUE THREAD

**Issue by JefferyLondon** [jupyter-xeus/xeus-python#271]
for `ipython` kernel, you can install kernels for different virtual environments:

    python -m ipykernel install --user --name myenv --display-name "Python (myenv)"

But `xpython` points to the environment where I started my Jupiter Lab. Is it possible to do the same in `xeus-python`?

**Comment by SylvainCorlay** [comment]
Hey @JefferyLondon thanks for posting here.

At the moment, we don't have a command to install from the environment where xpython is installed, but the general `jupyter kernelspec install` command works with the xpython kernel (we document it in the xeus-python documentation).

However, I agree that it would be useful to have something similar to `ipykernel install`.

**Comment by JefferyLondon** [comment]
Thank you. I can confirm the `jupyter kernelspec install` works, after modified python path in the `kernel.json` .

**Comment by enryH** [comment]
@JefferyLondon : Which python path did you set?

**Comment by JefferyLondon** [comment]
@enryH 
Just use the absolute path of the python execute in your virtual environment. 

you can get it by type `which python` in your venv
