### ISSUE TITLE
" AttributeError: type object 'kernel._Mock' has no attribute 'user_ns' " when trying to import functions from another notebook with ipynb.fs.defs

### ISSUE THREAD

**Issue by ThibaultLacharme** [jupyter-xeus/xeus-python#281]
Hello, I tried to use the new jupyter lab debugger, and switched to xeus-python's kernel for that purpose, but faced an issue when trying to work with several notebooks calling each other

To import functions from a notebook called `example_notebook.ipynb` in the same repository, using this syntax with python3 kernel works fine but doesn't with xpython:

`from ipynb.fs.defs.example_notebook import *`

which ultimately gives me the following error:

`AttributeError: type object 'kernel._Mock' has no attribute 'user_ns'`

For the record, I currently have xeus-python 0.7.1.

**Comment by martinRenou** [comment]
When I make a Notebook `test_notebook.ipynb` containing:
```python
def foo():
    print('yes')
```

I can import it from another Notebook without issues:
![ipynb](https://user-images.githubusercontent.com/21197331/83773295-a4437680-a684-11ea-8a07-aa6800bd2e85.png)

**Comment by ThibaultLacharme** [comment]
I personally still get this issue when doing the exact same thing as you did.

![xeus_python_import](https://user-images.githubusercontent.com/44061738/83785056-0b672800-a691-11ea-9fe9-123b86fc4adf.gif)
 
with the full error being:

![xeus_python_import](https://user-images.githubusercontent.com/44061738/83785724-0a82c600-a692-11ea-98ab-d3514c3d7be6.png)

I created both of these notebooks in a new folder under xpython.

Maybe it's related to my environment and all its dependencies, for now I got xeus 0.23.14 and jupyter lab 2.1.4.

**Comment by SylvainCorlay** [comment]
I think that the notebook importer project that you are using makes some assumptions on the kernel.

**Comment by ThibaultLacharme** [comment]
Do you mean it does not take into account the existence of another kernel except python3 ?

How could I modify that ?

**Comment by btel** [comment]
> Do you mean it does not take into account the existence of another kernel except python3 ?

you need to check the implementation of `test_notebook_import`, but most likely it does something like `get_ipython().user_ns`, which is not implemented in the current release of xpython.

Thus said:

this PR implements `user_ns` attribute on the xeus-python kernel: 

https://github.com/jupyter-xeus/xeus-python/pull/277. 

Can you check whether it solves this issue?

**Comment by ThibaultLacharme** [comment]
It might sound a bit dumb but: how can I replace in my current conda environment the xeus-python official release I have with the version from this PR ?

**Comment by martinRenou** [comment]
You need to pull @btel branch locally, and install the dev version of it using the development installation instructions

**Comment by ThibaultLacharme** [comment]
No problem @btel , I just don't work often enough on github so I tend to forget some things. I will try this and come back to you!

**Comment by btel** [comment]
no problem, let's wait when the PR will be merged (@SylvainCorlay ) and then it will be easier to test

**Comment by martinRenou** [comment]
This should hopefully not happen anymore. ipynb seems like a dead project anyway?
