### ISSUE TITLE
Wrap pybind11 headers

### ISSUE THREAD

**Issue by JohanMabille** [jupyter-xeus/xeus-python#283]
There is a [bug](https://bugs.python.org/issue36020) in Python 3.7 and 3.8 implementation where `snprintf` is defined as a macro on Windows. This definition is pulled in the code by pybind11 headers. This leads to compilation errors on recent Windows compilers when including other libraries that use `std::snprintf`.

A solution is to wrap pybind11 headers in a single header that undefines the macro. This should be done after #279 is merged.

**Comment by SylvainCorlay** [comment]
We have resolved this issue so far by always including nlohmann_json *before* pybind11.

**Comment by JohanMabille** [comment]
This is a very fragile solution, or rather a workaround. External contributors may not be aware of this.

**Comment by SylvainCorlay** [comment]
I agree. I reported this to the CPython folks: https://mail.python.org/archives/list/capi-sig@python.org/thread/5NXBZWKBMAPJJLNIXASSAYRIAP2OHJ53/

Also, nlohmann_json is premptively wrapping _snprintf in parenthesis for when it becomes a function-like macro.

cc @vstinner

**Comment by vstinner** [comment]
> I agree. I reported this to the CPython folks: https://mail.python.org/archives/list/capi-sig@python.org/thread/5NXBZWKBMAPJJLNIXASSAYRIAP2OHJ53/

And https://bugs.python.org/issue36020

So far, nobody proposed a fix.

**Comment by SylvainCorlay** [comment]
> So far, nobody proposed a fix.

What do you think of the proposal to make it a function-like macro?

**Comment by vstinner** [comment]
I proposed a fix: https://github.com/python/cpython/pull/20889 Please have a look and leave a comment there.

**Comment by JohanMabille** [comment]
BTW a workaround has been merged in pybind11, see https://github.com/pybind/pybind11/pull/2238.

Let's close this since the problem will disappear when pybind11 is released.
