### ISSUE TITLE
Look like xeus-python crash when trying to plot a pandas dataframe? 

### ISSUE THREAD

**Issue by the-oaks** [jupyter-xeus/xeus-python#301]
`import pandas as pd 
import numpy as np
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))
ts = ts.cumsum()
ts.plot()`

Does it mean we don't support Matplotlib? Thanks 

![image](https://user-images.githubusercontent.com/51134972/86522765-c9313200-be5a-11ea-883a-4ed592a78575.png)

**Comment by SylvainCorlay** [comment]
The matplotlib magic and inline is not (yet) supported as per #224, although the crash is not expected.

Closing to keep track of this in the main issue.
