### ISSUE TITLE
Switch from ptvsd to debugpy

### ISSUE THREAD

**Issue by JohanMabille** [jupyter-xeus/xeus-python#315]
debugpy is the drop-in replacement for ptvsd, which should be [deprecated](https://github.com/microsoft/ptvsd/pull/2125) soon.
Although debugpy is still in beta, it might be worth to test it in `xeus-python` and maybe provide a "beta" release of xeus-python with debupy as a hard dependency instead of  ptvsd.

cc @afshin @jtpio @SylvainCorlay

**Comment by edurenye** [comment]
Related to https://github.com/jupyter-xeus/xeus-python/issues/180

**Comment by jtpio** [comment]
Sounds good :+1: 

The latest versions of VS Code now use `debugpy` so it would indeed make sense for `xeus-python` to switch to it.
