### ISSUE TITLE
Input cache variable `_i` is not defined.

### ISSUE THREAD

**Issue by mike-matera** [jupyter-xeus/xeus-python#318]
Hello! 

Attempting to use the `_i` variable causes an error in the Xeus Python kernel. Is this a missing feature or the expected behavior? 

Thanks!

**Comment by SylvainCorlay** [comment]
Thanks for reporting! It is still a missing feature at the moment!

**Comment by mike-matera** [comment]
Thanks for the quick response. Would it help to leave this open?

**Comment by martinRenou** [comment]
Yes please :)
