### ISSUE TITLE
Invoking `IPython.display.display_html` on an HTML object renders repr representation

### ISSUE THREAD

**Issue by agoose77** [jupyter-xeus/xeus-python#324]
The following example
```python
import IPython.display
IPython.display.display_html(   
    IPython.display.HTML("<i>an html element</i>")
)
```
produces  `<display.HTML object at 0x7f33a5450630>`

**Comment by agoose77** [comment]
@martinRenou I think this is the culprit: https://github.com/jupyter-xeus/xeus-python/blame/42cb3ebf16b8b757570047de6bed00841a42ebc4/src/xdisplay.cpp#L58

The equality should be inverted?

**Comment by martinRenou** [comment]
Good catch! I guess you are right, it's been a long time already so the code is not crystal clear to me. But looking at it here, it makes sense to me.

Let me give it a quick try.

**Comment by martinRenou** [comment]
And thanks for looking into it! Sorry for not taking the time myself

**Comment by agoose77** [comment]
> And thanks for looking into it! Sorry for not taking the time myself

Please don't apologise - Open Source is a community effort! I just noticed that there isn't much additional code that runs when you execute `display_html` vs `display`, and I reproduced the bug by passing in `text/html` in the `include` parameter to `display()`.
