### ISSUE TITLE
getpass() displaying text

### ISSUE THREAD

**Issue by kafonek** [jupyter-xeus/xeus-python#325]
`import getpass; getpass.getpass()` is displaying what I type in the input box as a type it rather than obfuscating with dots.  I was able to see that behavior in Binder.

**Comment by martinRenou** [comment]
This doesn't seem to be an issue anymore using latest xeus-python

![getpass](https://user-images.githubusercontent.com/21197331/132825096-d7497283-7561-42e0-9ba3-4042c98b0609.gif)

**Comment by kafonek** [comment]
thanks for the follow up @martinRenou !

**Comment by martinRenou** [comment]
> xeus-python: 0.15.8 (the newest version on PyPI, but 0.15.10 is on GitHUb)

It seems we need to build some wheels indeed.

> xeus-python-shell: 0.5.0

Can you try upgrading this one to the latest?

**Comment by JulianWgs** [comment]
Thanks for the quick response!

I updated `xeus-python-shell` and got this error:
```
xeus-python 0.15.8 requires xeus-python-shell[ipython]<0.6,>=0.5, but you have xeus-python-shell 0.6.1 which is incompatible.
```

Nonetheless after restarting Jupyter the issue persists. I didn't have any other issues due to the upgrade.

**Comment by martinRenou** [comment]
What is your IPython version?

**Comment by JulianWgs** [comment]
My IPython version was 8.9.0. Then I upgraded to 8.16.1 and the bug is unfortunately still present.
