### ISSUE TITLE
Please update jedi

### ISSUE THREAD

**Issue by stefaneidelloth** [jupyter-xeus/xeus-python#345]
python-language-server 0.35.1 requires jedi<0.18.0,>=0.17.0, but you'll have jedi 0.15.2 which is incompatible.

xeus-python 0.8.3 requires jedi<0.16,>=0.15.1, but you'll have jedi 0.17.2 which is incompatible.

**Comment by SylvainCorlay** [comment]
@stefaneidelloth thanks. Would you like to open a PR?

**Comment by SylvainCorlay** [comment]
Closing as fixed. Next version will not have such constraints on jedi or pygments
