### ISSUE TITLE
Output caching: "name '_' is not defined"

### ISSUE THREAD

**Issue by bsdz** [jupyter-xeus/xeus-python#359]
I am using xeus-python 0.9.0 and when I try accessing output cache variables (ie _<n> or _) I receive a NameError and the variables are undefined. In IPython these variables are [automatically generated on 1st invocation](https://ipython.readthedocs.io/en/stable/interactive/reference.html#output-caching-system). It's quite a useful feature.

**Comment by martinRenou** [comment]
Thanks for the report, it would indeed be nice to have
