### ISSUE TITLE
ImportError: cannot import name 'Image' from 'IPython.display'. error only occurs with xeus-python kernel

### ISSUE THREAD

**Issue by gunstonej** [jupyter-xeus/xeus-python#392]
see this issue (text copied below):
https://github.com/ipython/ipython/issues/12561

i just remade the xeus-python env from scratch and got the same issue.

```
i'm getting some strange behaviour -

i'm testing a xeus-python environment,

in a jupyterlab notebook, if i type
from IPython.display import display, JSON, Markdown, HTML, display_pdf, clear_output

i get no issues, but:
from IPython.display import Image

returns

ImportError Traceback (most recent call last)
In [15]:
Line 1: from IPython.display import Image

ImportError: cannot import name 'Image' from 'IPython.display' (C:\Users\j.gunstone\Miniconda3\envs\jupyterlab-debugger\lib\site-packages\IPython\display.py)

in any other environment importing Image as shown works with no issue.

here is a explicit spec file of my environment
jupyterlab-debugger.txt

```
[jupyterlab-debugger.txt](https://github.com/jupyter-xeus/xeus-python/files/5875278/jupyterlab-debugger.txt)

**Comment by martinRenou** [comment]
Thanks for reporting!
This à known issue. I was actually planning on working on this tomorrow.

**Comment by TOMIVIY** [comment]
I have the same issue except I'm trying to do:

from IPython.core.display import display_pretty

@martinRenou is this an issue of needing to update my xeus python version?
