### ISSUE TITLE
input isn't blocking

### ISSUE THREAD

**Issue by akhmerov** [jupyter-xeus/xeus-python#394]
I observe that on xeus 0.25.3, xeus-python 0.9.4, and jupyterlab 3 executing

```
input()
```
immediately returns an empty line without waiting for an actual input.

**Comment by martinRenou** [comment]
This does not seem to be an issue with latest xeus-python. Feel free to reopen if you can still reproduce.

![input](https://user-images.githubusercontent.com/21197331/132822751-8f1621f5-fb55-436c-bfb5-78e0d1c9706c.gif)

**Comment by akhmerov** [comment]
Awesome, I confirm—it's all fixed! Always great when issues magically get resolved as things develop :)
