### ISSUE TITLE
Automatic import of libraries at startup

### ISSUE THREAD

**Issue by jnarula5** [jupyter-xeus/xeus-python#402]
Hi,

In IPython, I can automatically import libraries into jupyter notebook by defining start.py under ~/.ipython/profile_default/startup (https://towardsdatascience.com/how-to-automatically-import-your-favorite-libraries-into-ipython-or-a-jupyter-notebook-9c69d89aa343)

I could not locate the config to the same for an xpython kernel.

Please help.

Thanks,
JN

**Comment by martinRenou** [comment]
This should be fixed with xeus-python 0.11.0. xeus-python should now support IPython config files. Feel free to reopen this issue if you find a problem.
