### ISSUE TITLE
Statement of compatibility

### ISSUE THREAD

**Issue by michaelaye** [jupyter-xeus/xeus-python#436]
Hi!
I'd love to use xeus-Python for its debugging capability but I can't get a feel for what is and what is not working in the (Sci-)Python ecosphere switching from a standard kernel to xpython. Could we maybe have a simple bullet-listed doc page that lists what the differences to a standard Python kernel are in terms of what's working and what not? Apologies if I missed it but I looked for an intro page like that but couldn't find it. Something that makes me understand if I should/could be using xpython in daily production, what principal things have not been implemented yet compared to the classic kernels etc.  At the moment, it's just very vague for the outsider to judge where this project is at. 
Thanks for all your hard work!
Michael

**Comment by martinRenou** [comment]
Hi :) 

You should see no difference between xeus-python and ipykernel

**Comment by michaelaye** [comment]
Are all ipython %magics implemented or is that strictly speaking not an ipykernel question?

--
Michael Aye
LASP / CU Boulder

**Comment by JohanMabille** [comment]
`xeus-python` internally uses `IPython`  as the interpreter, so all the magics should work.

**Comment by SylvainCorlay** [comment]
Closing as answered!
