### ISSUE TITLE
%matplotlib inline not working?

### ISSUE THREAD

**Issue by brandon-68** [jupyter-xeus/xeus-python#441]
### Software are as follow
Python 3.6
Jupyterlab3.0

### Issue
When I key in this command, `%matplotlib inline`, this error appears

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
In  [2]:
Line 1:     %matplotlib inline

ValueError: magics not found

---------------------------------------------------------------------------

**Comment by SylvainCorlay** [comment]
Please update to Python 3.7 or later. The latest version of xeus-python, which supports the matplotlib magics, was not packaged for python 3.6.

**Comment by brandon-68** [comment]
Okok, thanks!
