### ISSUE TITLE
How to construct URL for mybinder.org?

### ISSUE THREAD

**Issue by abitrolly** [jupyter-xeus/xeus-python#457]
I've tried to set `xeus-python` in `requirement.txt`, but that doesn't help, and binder is still loaded with default Python kernel.

https://mybinder.org/v2/gist/abitrolly/2b5351962b3b6ed57ce7141599fcde7e/HEAD?filepath=gql-pagination.ipynb

**Comment by martinRenou** [comment]
You should add it to your `environment.yml` file, like we do here https://github.com/jupyter-xeus/xeus-python/blob/master/environment.yml

**Comment by abitrolly** [comment]
But I don't use `conda`. How does Binder decide which kernel is selected? I couldn't find any explicit references to `xeus` in https://github.com/jupyterhub/repo2docker

**Comment by martinRenou** [comment]
Binder uses conda, so you can use it. And it's actually better than pip, especially for installing a C++ package like xeus-python.

> How does Binder decide which kernel is selected?

Binder doesn't decide anything. The Jupyter frontend you use (notebook or jupyterlab) will find if xeus-python is installed and allow you to use it.

If you already saved your notebooks using xeus-python, then it will use xeus-python automatically if it finds it.
If you saved your notebooks using the default Python kernel, then you will need to manually switch to xeus-python in the UI. In the kernel options.
