### ISSUE TITLE
Do not pollute global namespace on `richInspectVariables`

### ISSUE THREAD

**Issue by krassowski** [jupyter-xeus/xeus-python#460]
Testing https://github.com/jupyterlab/jupyterlab/pull/10299 with latest xeus-python I noticed that extra variables are added to namespace after each inspection of an object (`*_repr_data` and `*_repr_metadata`). The variables are last used in:

https://github.com/jupyter-xeus/xeus-python/blob/9fb669ff6f74d05fe7e76e08b592c3f465b922cc/src/xdebugger.cpp#L206-L223

![polluting](https://user-images.githubusercontent.com/5832902/123296623-b5208d80-d50e-11eb-8c17-cca06f9679a6.gif)

And seem not to be cleared after the reply body is constructed. Can we remove these variables from the global namespace, or at the very least prefix them with an underscore (`_`)?

**Comment by krassowski** [comment]
I would be to send a PR if removing them is fine.

**Comment by JohanMabille** [comment]
Indeed this looks like an oversight, these variables should definitely be removed. Thanks for catching it!
