### ISSUE TITLE
Custom Xeus-Python does not connect to jupyter client 

### ISSUE THREAD

**Issue by Yamanee** [jupyter-xeus/xeus-python#465]
I want to make my own custom jupyter server for python based on `xpyt::interpreter` but I can't make it work for some reason. I basically took the main.cpp file of the `xeu-calc` project, replace their interpreter with `xpyt::interpreter` but jupyter cannot connect to it. See attached for the log that jupyter gives me, complete source code as well as my kernel configuration.

main.cpp : 
```cpp
[...]
std::string file_name = (argc <= 1) ? "connection.json" : argv[2];
xeus::xconfiguration config = xeus::load_configuration(file_name);
auto interpreter = std::unique_ptr<xpyt::interpreter>(new xpyt::interpreter());
xeus::xkernel kernel(config, xeus::get_user_name(), std::move(interpreter));
kernel.start();
[...]
```

System:
 - Python : 3.8
 - Custom build of xeus-python (against Python system) : commit a9400522fc2ff61cdb0a536b8db9f4ccbb2f1a2d (master from May 2021)
 - jupyter core : 4.6.3
 - jupyter-notebook : 6.0.3

Is this a bug or am I missing something here ?

[xeusPythonIssue.zip](https://github.com/jupyter-xeus/xeus-python/files/6962743/xeusPythonIssue.zip)

**Comment by Yamanee** [comment]
I got 

```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

There's no jupyter client launched when I ran my binary and my `connection.json` looks like this (this is inspired from the one created automatically by  jupyter notebook client) :

```json
{
  "shell_port": 59859,
  "iopub_port": 55017,
  "stdin_port": 53767,
  "control_port": 44809,
  "hb_port": 43099,
  "ip": "127.0.0.1",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "testserver"
}
```

**Comment by martinRenou** [comment]
Can you try to track which line is causing this error in your code? With this old-fashion debugging tool named `std::cout` 😄

**Comment by Yamanee** [comment]
Sorry I have not been very active !

Anyway after a bit more tracking here is the trace I got using GDB :

```gdb
(gdb) bt
#0  0x00007ffff73ffc27 in _PyObject_GC_New () from /usr/lib/libpython3.9.so.1.0
#1  0x00007ffff74020b8 in PyDict_New () from /usr/lib/libpython3.9.so.1.0
#2  0x00007ffff7401ff4 in PyUnicode_InternInPlace () from /usr/lib/libpython3.9.so.1.0
#3  0x00007ffff7400731 in PyUnicode_InternFromString () from /usr/lib/libpython3.9.so.1.0
#4  0x00007ffff745cde3 in PyImport_Import () from /usr/lib/libpython3.9.so.1.0
#5  0x00007ffff74db34d in PyImport_ImportModule () from /usr/lib/libpython3.9.so.1.0
#6  0x00007ffff7ec963f in pybind11::module_::import (name=0x7ffff7f63209 "sys")
    at /usr/include/pybind11/pybind11.h:1017
#7  0x00007ffff7f2d8b2 in xpyt::interpreter::redirect_output (this=0x5555555b84a0)
    at /home/timothee/Dev/XEUS/xeus-python/src/xinterpreter.cpp:417
#8  0x00007ffff7f2a1df in xpyt::interpreter::interpreter (this=0x5555555b84a0, 
    redirect_output_enabled=true, redirect_display_enabled=true)
    at /home/timothee/Dev/XEUS/xeus-python/src/xinterpreter.cpp:52
#9  0x000055555558d7df in std::make_unique<xpyt::interpreter> ()
    at /usr/include/c++/11.1.0/bits/unique_ptr.h:962
#10 0x000055555558b6ac in main (argc=3, argv=0x7fffffffe298)
    at /home/timothee/tmp/xeusPythonIssue/main.cxx:19
```

This codepath was only taken if `redirect_output_enabled==true` so I constructed my interpreter with parameters `(false,true)` but then the creation of the kernel also crashed when calling `pybind11::gil_scoped_release` so I guess the problem is coming from my `pybind11` installation or linking. This behavior is coming from both my ArchLinux machine and my Ubuntu machine.

So I guess my question in this thread is : what is the correct way of building xeus-python ? I built manually all of my dependancies (ie xeus, pybind11-json, cppzmq, xtl) except `pybind11` which is the system-wide one. Is this a standard way to go ?

**Comment by martinRenou** [comment]
Maybe @JohanMabille can help here?

**Comment by JohanMabille** [comment]
Looks like there's a mix of Python versions (3.8 in the original post, 3.9 in the logs).

The best way to track this kind of problems is to download the dependencies from conda-forge and build xeus-python only. If that works, then the issue comes from a global build problem (and that might not be an easy one to fix, we spent weeks to have a full build (i.e xeus-python and dependencies) working).

**Comment by Yamanee** [comment]
Couldn't make it work so far but doesn't seem to be an issue from xeus-python. Closing
