### ISSUE TITLE
Edit default profile configuration of xeus-python

### ISSUE THREAD

**Issue by cristmal** [jupyter-xeus/xeus-python#469]
When I want to edit the configuration of the profile in `ipython`, I can edit the directory `~/.ipython/profile_default`.
I didn't find a similar configuration directory when speaking about xeus.

My usecase:
I want to run a constant code at the startup of any script that will be run by `xeus`.

If I used `ipython`, I could change the `~/ipython/profile_default/startup` directory.
How may I use this feature in `xeus-python`?

**Comment by martinRenou** [comment]
xeus-python makes use of IPython, so your `~/.ipython/profile_default` config *should* be picked up.
