### ISSUE TITLE
Xeus Python icon too dark?

### ISSUE THREAD

**Issue by Daksol** [jupyter-xeus/xeus-python#512]
Xeus python, and the debugging features it enables in Jupyter Lab, is just great.

But the Xeus Python icon is really dark, and does not show up clearly in many desktop colour schemes.

So worth creating an alternative icon, but in brighter colours for user on darker themes ?
![Xeus_icon_asPNG](https://user-images.githubusercontent.com/42010857/141140531-015c112a-c7da-4d65-8a35-00ad365b2fc1.PNG)
?

**Comment by JohanMabille** [comment]
Yes, definitely ;) I guess an option could be to replace the dark gray with a light gray, and keep the background transparent?

**Comment by Daksol** [comment]
That sounds a good option tho, at risk of being flippant, there are 16+ million colours out there so we are not limited to shades of grey.

But if this issue is typical of those being raised about Xeus and friends, the project is probably doing pretty well

**Comment by martinRenou** [comment]
> at risk of being flippant, there are 16+ million colours out there so we are not limited to shades of grey.

Here, I fixed it for you: 

![42010857](https://user-images.githubusercontent.com/21197331/141967965-d08982a7-1823-4bf1-8a5d-8698bd39decb.png)

Jokes apart, I agree some color wouldn't harm :) Maybe using the same color as the xeus logo?

**Comment by SylvainCorlay** [comment]
I think that the practice is to use the logo from the programming language. We should probably use the unmodified Python logo for xpython.
