### ISSUE TITLE
debugger.set_exception_breakpoints test fails

### ISSUE THREAD

**Issue by doronbehar** [jupyter-xeus/xeus-python#524]
It fails with the following error here on NixOS:

```
[       OK ] debugger.set_exception_breakpoints (4411 ms)
[ RUN      ] debugger.source
registering handler for SIGSEGV
PYTHONHOME set to /nix/store/jhy9hvk80awxmf37hwbxqghqm5vavfrh-python3-3.9.10-env
terminate called after throwing an instance of 'zmq::error_t'
  what():  Address already in use
Unit test time out !!
```

I compiled xeus-python 0.13.6 with cppzmq 4.8.1 but the error occours with cppzmq 4.4.1 as well. I also used https://github.com/jupyter-xeus/xeus-python/pull/523 - that's why the PYTHONHOME is set to that Nix path.

cc @JohanMabille

**Comment by JohanMabille** [comment]
I would bet on the test starting while the kernel from the previous test has not shutdown yet. Do you still have the issue if you run this test alone (i.e passing the option `--gtestfilter=debugger.set_exception_breakpoints`) ?

**Comment by doronbehar** [comment]
> I would bet on the test starting while the kernel from the previous test has not shutdown yet. Do you still have the issue if you run this test alone (i.e passing the option `--gtestfilter=debugger.set_exception_breakpoints`) ?

I'm sorry @JohanMabille but I'm not sure, what command exactly to run? NixOS builds packages inside a sandbox where it's a bit hard to imitate what's going on in there but I will try my best if I'll know what command should accept that flag.

**Comment by JohanMabille** [comment]
The command to run the test is `./test_xeus_python`, you can pass the following (there was actually a mistake in my previous comment, the test that fails is `source`): `./test_xeus_python --gtestfilter=debugger.source`.

Also do you have this failure each time you run the tests, on the same test?

**Comment by doronbehar** [comment]
@JohanMabille  I'm experiencing the same test failure consistently every time I run the build, and also when I enter the build environment in which the test was run, and execute `./test_xeus_python --gtestfilter=debugger.source`:

```
[       OK ] debugger.set_exception_breakpoints (4470 ms)
[ RUN      ] debugger.source
registering handler for SIGSEGV
PYTHONHOME set to /nix/store/jhy9hvk80awxmf37hwbxqghqm5vavfrh-python3-3.9.10-env
Starting xeus-python kernel...

If you want to connect to this kernel from an other client, you can use the kernel-debug.json file.
Run with XEUS 2.3.1
XDEBUGGER: the debugger has started
XDEBUGGER: dumped /build/xpython_1641/4104358117.py
Unit test time out !!
terminate called without an active exception
Aborted (core dumped)

[nixbld@localhost:/var/lib/cntr/build/source/build/test]$ echo $?
134
```

I did however managed to solve the issue with this patch:

```patch
diff --git i/test/test_debugger.cpp w/test/test_debugger.cpp
index 7710ddd..a72350a 100644
--- i/test/test_debugger.cpp
+++ w/test/test_debugger.cpp
@@ -1133,7 +1133,7 @@ TEST(debugger, set_exception_breakpoints)
         debugger_client deb(context, KERNEL_JSON, "debugger_set_exception_breakpoints.log");
         bool res = deb.test_set_exception_breakpoints();
         deb.shutdown();
-        std::this_thread::sleep_for(2s);
+        std::this_thread::sleep_for(5s);
         EXPECT_TRUE(res);
         notify_done();
     }
```

Would you like to see this in a patch? Or perhaps 5 seconds is too much?

**Comment by JohanMabille** [comment]
I think it's fine for now, we need to rewrite these tests anyway.
