### ISSUE TITLE
Implement showtraceback

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus-python#62]
A `showtraceback` function should be added in `xeus-python`. It's used by `ipywidgets` https://github.com/jupyter-widgets/ipywidgets/blob/master/ipywidgets/widgets/widget.py#L191.
An error is thrown when this code is triggered.

**Comment by SylvainCorlay** [comment]
https://github.com/ipython/ipython/blob/7.3.0/IPython/core/interactiveshell.py#L1996
