### ISSUE TITLE
No Kernel

### ISSUE THREAD

**Issue by tpike3** [jupyter-xeus/xeus-python#625]
I feel like this is going to be really obvious, but I cannot get a kernel to appear in the Mesa-Geo docs. JupyterLite opens but there is no kernel options for selection

https://mesa-geo-test.readthedocs.io/en/latest/tutorials/overview.html 

My conf.py is here https://github.com/tpike3/mesa-geo/blob/newsphinx/docs/source/conf.py 

I am a little desperate as I am running a tutorial on Wednesday and would like to use jupyterlite instead of Colab. 

Thank you

**Comment by martinRenou** [comment]
Thanks for opening an issue!

Would you be able to provide jupyterlite build logs?

Also this file https://github.com/tpike3/mesa-geo/blob/newsphinx/docs/source/.jupyterlite.doit.db makes me unconfortable, I would remove it from the repo and make a `.gitignore ` entry to make sure to not commit it again. It may be the culprit.

**Comment by tpike3** [comment]
Thanks @martinRenou! Please see attached  `.jupyterlite.doit.db` removed

[log-debug.txt](https://github.com/user-attachments/files/15545216/log-debug.txt)

Regarding the log. I have had the `jupyter-lite.json` not found error before and manually replicated the file. However, I get different missing file errors so after "fixing" the one in the log I get this ` No such file or directory \mesa-geo\\docs\\_output\\build\\html\\jupyter-lite.json'`

**Comment by tpike3** [comment]
I attached part of the read the docs build and it may be because read the docs is installing via `pip` which is experimental as the documentation says, so I will give that a try. 
[readthedocs build.txt](https://github.com/user-attachments/files/15594630/readthedocs.build.txt)

**Comment by tpike3** [comment]
OK, I figured out the issue, You have to use miniconda or mamba, not standard python to build out the kernel --https://stackoverflow.com/questions/69774313/why-does-rtd-run-python-env-create-instead-of-conda-env-create-when-building; https://github.com/readthedocs/readthedocs.org/pull/10672
