### ISSUE TITLE
Implement magic commands

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus-python#63]
Line magics:

- [ ] %alias  
- [ ] %alias_magic  
- [ ] %autoawait  
- [ ] %autocall  
- [ ] %automagic  
- [ ] %autosave  
- [ ] %bookmark  
- [x] %cat  
- [x] %cd  
- [ ] %clear  
- [ ] %colors  
- [ ] %config  
- [ ] %connect_info  
- [ ] %cp  
- [ ] %debug  
- [ ] %dhist  
- [ ] %dirs  
- [ ] %doctest_mode  
- [ ] %ed  
- [ ] %edit  
- [ ] %env  
- [ ] %gui  
- [ ] %hist  
- [x] %history  
- [ ] %killbgscripts  
- [ ] %ldir  
- [ ] %less  
- [ ] %lf  
- [ ] %lk  
- [ ] %ll  
- [ ] %load  
- [x] %load_ext  
- [ ] %loadpy  
- [ ] %logoff  
- [ ] %logon  
- [ ] %logstart  
- [ ] %logstate  
- [ ] %logstop  
- [ ] %ls  
- [ ] %lsmagic  
- [ ] %lx  
- [ ] %macro  
- [ ] %magic  
- [ ] %man  
- [ ] %matplotlib  
- [ ] %mkdir  
- [ ] %more  
- [ ] %mv  
- [ ] %notebook  
- [ ] %page  
- [ ] %pastebin  
- [ ] %pdb  
- [ ] %pdef  
- [ ] %pdoc  
- [ ] %pfile  
- [ ] %pinfo  
- [ ] %pinfo2  
- [ ] %popd  
- [ ] %pprint  
- [ ] %precision  
- [ ] %prun  
- [ ] %psearch  
- [ ] %psource  
- [ ] %pushd  
- [x] %pwd  
- [ ] %pycat  
- [ ] %pylab  
- [ ] %qtconsole  
- [ ] %quickref  
- [x] %recall  
- [ ] %rehashx  
- [ ] %reload_ext  
- [ ] %rep  
- [x] %rerun  
- [ ] %reset  
- [ ] %reset_selective  
- [ ] %rm  
- [ ] %rmdir  
- [ ] %run  
- [ ] %save  
- [ ] %sc  
- [ ] %set_env  
- [ ] %store  
- [ ] %sx  
- [ ] %system  
- [ ] %tb  
- [ ] %time  
- [ ] %timeit  
- [ ] %unalias  
- [ ] %unload_ext  
- [ ] %who  
- [ ] %who_ls  
- [ ] %whos  
- [ ] %xdel  
- [ ] %xmode

Cell magics:

- [ ] %%!  
- [ ] %%HTML  
- [ ] %%SVG  
- [ ] %%bash  
- [ ] %%debug  
- [ ] %%file  
- [ ] %%html  
- [ ] %%javascript  
- [ ] %%js  
- [ ] %%latex  
- [ ] %%capture  
- [ ] %%markdown  
- [ ] %%perl  
- [ ] %%prun  
- [ ] %%pypy  
- [ ] %%python  
- [ ] %%python2  
- [ ] %%python3  
- [ ] %%ruby  
- [ ] %%script  
- [ ] %%sh  
- [ ] %%svg  
- [ ] %%sx  
- [ ] %%system  
- [ ] %%time  
- [x] %%timeit  
- [x] %%writefile

**Comment by SylvainCorlay** [comment]
Note for reference:

- We discussed actually reusing the magics from IPython with the `%%` prefix when IPython is installed.
- We should enable non-language-specific magics in xeus, where the magics prefix would be setable for each language. For example, a timeit implementation can make sense for any kernel.

**Comment by afshin** [comment]
Would it be insane to make `ipykernel` a dependency of `xeus-python` to use its magic logic until it is implemented natively?

**Comment by martinRenou** [comment]
Maybe not make it a dependency but use it if it's available?

**Comment by SylvainCorlay** [comment]
Note: we would probably only need IPython and not ipykernel.

**Comment by afshin** [comment]
If it's *just* `ipython`, that makes it even more compelling to have it be a dependency, because it won't even appear as a kernel in users' notebook/lab clients. And since it's a pure python package, it seems fairly uncontroversial.

**Comment by dbalabka** [comment]
@SylvainCorlay currently, all magic commands rise parsing error. It would be great to just ignore these commands during runtime, otherwise, it is blocking the developer to use this kernel for debugging purposes.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay currently, all magic commands rise parsing error. It would be great to just ignore these commands during runtime for now, otherwise, it is blocking the developer to use this kernel for debugging purposes.

That is an excellent suggestion! I think we will start with that.

**Comment by peterquirk** [comment]
Don't forget the ! magic.

**Comment by AntoineToussaint** [comment]
Not sure about other people, but for me:
```
%load_ext autoreload
%autoreload
```
is the big one. But maybe there is a better way to reload a function that has been modified?

**Comment by jhettler** [comment]
Please, don't forget to implement sql magics https://github.com/catherinedevlin/ipython-sql. Thanks!

**Comment by pratikchhapolika** [comment]
magic command still not working?

**Comment by jtpio** [comment]
@pratikchhapolika some are now implemented and can be tested on Binder:

https://mybinder.org/v2/gh/jupyter-xeus/xeus-python/stable?filepath=notebooks/xeus-magics.ipynb

**Comment by pratikchhapolika** [comment]
Version=0.8.0 ?

**Comment by jtpio** [comment]
@pratikchhapolika You can use 0.8.2 (the latest at the moment)

**Comment by william-davies** [comment]
> Not sure about other people, but for me:
> 
> ```
> %load_ext autoreload
> %autoreload
> ```
> 
> is the big one. But maybe there is a better way to reload a function that has been modified?

Just wanted to follow up on this. `%load_ext autoreload` still doesn't work for me. Am I doing something wrong or is it just not supported at the moment? If the latter is the case, what's the timeline for supporting it? Thank you very much!
![Screenshot 2020-11-06 at 07 58 32](https://user-images.githubusercontent.com/36384318/98340845-e7c05900-2005-11eb-84cd-a2c7fb497e79.jpg)

**Comment by mherkazandjian** [comment]
may you also consider adding support for matlplotlib widgets, i.e not just matplotlib inline magic.

````jupyter
%matplotlib widget
````

**Comment by Hoeze** [comment]
Hi, is there any ongoing work on magic commands in xeus-python?
I.e. can we expect them anytime soon to work?

I'd really like to try out the jupyterlab debugger, but I cannot when the magics don't work then...

**Comment by SylvainCorlay** [comment]
The magics extension system has been ported to xeus-python, and most custom magics willl work out of the box.

However, the matplotlib magics and other core magics of IPython have not been integrated as they rely a lot of specific ipython internals. There is ongoing work for matplotlib specifically.

**Comment by Hoeze** [comment]
Thanks for the update @SylvainCorlay!
