### ISSUE TITLE
wasm streaming compile failed: LinkError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by LiamBindle** [jupyter-xeus/xeus-python#639]
Hi,

First off, thanks for all of your work on xeus-python.

I'm using [voici](https://github.com/voila-dashboards/voici) to convert some notebooks into HTML files that are hosted as a static website, but recently I started running into the following error when I try to access the HTML files via my website (S3+CloudFront).

```
wasm streaming compile failed: LinkError: WebAssembly.instantiate(): table import 488 is smaller than initial 8930, got 8874
```

I'm trying to figure out what this means and I'm going in circles. Any ideas?

The function that's raising the exception is `instantiateAsync()` in xpython.js. Here is a screenshot of the console errors when I try to load a page from my website.

![image](https://github.com/user-attachments/assets/bcdf9988-5c2f-4061-96eb-0501a94e2c73)

I can reproduce the error with a simple notebook that is `print("Hello world")`  and the only package that is installed is `xeus-python`. The error only happens when I try to access the file from the website---when I try to access the local HTML files it works okay. 

Is anyone able to point me in the right direction?

**Comment by LiamBindle** [comment]
This is a red herring. I removed all of my pinned versions of libraries and that fixed the problem.

**Comment by martinRenou** [comment]
Ah good to hear!
