### ISSUE TITLE
I have two similarly setup builds, and I can't read files in one

### ISSUE THREAD

**Issue by paddymul** [jupyter-xeus/xeus-python#643]
For my own project fails with this line:
`df = pd.read_csv("./yellow_tripdata_2021-02.csv")`
on
https://paddymul.github.io/buckaroo-examples/lab/index.html?path=Full-tour.ipynb  

Jupyter can read "./yellow_tripdata_2021-02.csv"

On Julia Evans pandas-cookbook, which I created following a very similar template.  reading csvs works fine.
Any idea what I'm doing wrong?
look here
https://jvns.github.io/pandas-cookbook/lab/index.html?path=Chapter+1+-+Reading+from+a+CSV.ipynb

original repos here
https://github.com/paddymul/buckaroo-examples
https://github.com/jvns/pandas-cookbook

**Comment by jtpio** [comment]
Thanks @paddymul for sharing these repos, they look nice.

Trying https://paddymul.github.io/buckaroo-examples/lab/index.html?path=Full-tour.ipynb in a Firefox regular seems to be working:

![image](https://github.com/user-attachments/assets/a38a427d-81bf-4538-95d1-bb9e2b331426)

Maybe it's related to some browser caching issues, which often leads to issues related to accessing content?

**Comment by paddymul** [comment]
Thank you.  After clearing my cache I got it to work.
